apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-gxqn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-gxqn
    app.kubernetes.io/part-of: build-suite-test-application-amko
  name: test-annotations-gxqn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-gxqn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-gxqn
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-ziio-tenant/build-suite-test-application-amko/test-annotations-gxqn@sha256:aa5a8b5c5ceb95f49afcac05fd0ef8d20955a463d0c733541bb729c3de942223
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
